import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React from "react";
import { useSelector } from "react-redux";
import { RootState } from "../src/store";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();

  const token = useSelector((state: RootState) => state.firebaseSlice.token);

  React.useEffect(() => {
    if (token) {
      router.push("/home");
    }
    if (token === null) {
      router.push("/login");
    }
  }, [token]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Epop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
